name: Build and Release ZXP

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Create ZXP package
      run: npm run zxp
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: AI SFX Generator ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## AI SFX Generator ${{ steps.get_version.outputs.VERSION }}
          
          ### Installation
          1. Download the .zxp file below
          2. Close Premiere Pro if running
          3. Double-click the .zxp file to install via Adobe Extension Manager
          4. Restart Premiere Pro
          
          ### What's New
          See the commit history for detailed changes in this release.
          
          ---
          **Compatible with**: Adobe Premiere Pro 2020-2025
          **Built with**: Bolt CEP Framework
        draft: false
        prerelease: false
        
    - name: Upload ZXP Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/zxp/ai-sfx-generator.zxp
        asset_name: ai-sfx-generator-${{ steps.get_version.outputs.VERSION }}.zxp
        asset_content_type: application/zip